// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"spurt-cms/graphql/scalars"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

type AdditionalFields struct {
	Sections []Section `json:"sections,omitempty"`
	Fields   []Field   `json:"fields,omitempty"`
}

type Author struct {
	ID               int        `json:"id"`
	FirstName        string     `json:"firstName"`
	LastName         string     `json:"lastName"`
	Email            string     `json:"email"`
	MobileNo         *string    `json:"mobileNo,omitempty"`
	IsActive         *int       `json:"isActive,omitempty"`
	ProfileImagePath *string    `json:"profileImagePath,omitempty"`
	CreatedOn        time.Time  `json:"createdOn"`
	CreatedBy        int        `json:"createdBy"`
	ModifiedOn       *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy       *int       `json:"modifiedBy,omitempty"`
	TenantID         string     `json:"tenantId"`
	RoleID           *int       `json:"roleId,omitempty"`
	RoleName         *string    `json:"roleName,omitempty"`
	NameString       *string    `json:"NameString,omitempty"`
}

type Category struct {
	ID           int        `json:"id"`
	CategoryName string     `json:"categoryName"`
	CategorySlug string     `json:"categorySlug"`
	Description  string     `json:"description"`
	ImagePath    string     `json:"imagePath"`
	CreatedOn    time.Time  `json:"createdOn"`
	CreatedBy    int        `json:"createdBy"`
	ModifiedOn   *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy   *int       `json:"modifiedBy,omitempty"`
	ParentID     int        `json:"parentId"`
	TenantID     string     `json:"tenantId"`
}

type CategoryDetails struct {
	Categorylist []Category `json:"categorylist"`
	Count        int        `json:"count"`
}

type CategoryFilter struct {
	CategoryGroupID      graphql.Omittable[*int]    `json:"categoryGroupId,omitempty"`
	HierarchyLevel       graphql.Omittable[*int]    `json:"hierarchyLevel,omitempty"`
	ExcludeGroup         graphql.Omittable[*bool]   `json:"excludeGroup,omitempty"`
	ExcludeParent        graphql.Omittable[*bool]   `json:"excludeParent,omitempty"`
	ExactLevelOnly       graphql.Omittable[*bool]   `json:"exactLevelOnly,omitempty"`
	CheckEntriesPresence graphql.Omittable[*bool]   `json:"checkEntriesPresence,omitempty"`
	CategoryGroupSlug    graphql.Omittable[*string] `json:"categoryGroupSlug,omitempty"`
	ChannelSlug          graphql.Omittable[*string] `json:"channelSlug,omitempty"`
}

type Channel struct {
	ID                 int        `json:"id"`
	ChannelName        string     `json:"channelName"`
	ChannelDescription string     `json:"channelDescription"`
	SlugName           string     `json:"slugName"`
	FieldGroupID       int        `json:"fieldGroupId"`
	IsActive           int        `json:"isActive"`
	CreatedOn          time.Time  `json:"createdOn"`
	CreatedBy          int        `json:"createdBy"`
	IsDeleted          int        `json:"isDeleted"`
	ModifiedOn         *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy         *int       `json:"modifiedBy,omitempty"`
	TenantID           string     `json:"tenantId"`
}

type ChannelDetails struct {
	Channellist []Channel `json:"channellist"`
	Count       int       `json:"count"`
}

type ChannelEntries struct {
	ID               int                  `json:"id"`
	Title            string               `json:"title"`
	Slug             string               `json:"slug"`
	Description      scalars.CustomString `json:"description"`
	UserID           int                  `json:"userId"`
	ChannelID        int                  `json:"channelId"`
	Status           int                  `json:"status"`
	IsActive         int                  `json:"isActive"`
	CreatedOn        time.Time            `json:"createdOn"`
	CreatedBy        int                  `json:"createdBy"`
	ModifiedBy       *int                 `json:"modifiedBy,omitempty"`
	ModifiedOn       *time.Time           `json:"modifiedOn,omitempty"`
	CoverImage       string               `json:"coverImage"`
	ThumbnailImage   string               `json:"thumbnailImage"`
	MetaTitle        string               `json:"metaTitle"`
	MetaDescription  string               `json:"metaDescription"`
	Keyword          string               `json:"keyword"`
	CategoriesID     string               `json:"categoriesId"`
	RelatedArticles  string               `json:"relatedArticles"`
	FeaturedEntry    int                  `json:"featuredEntry"`
	ViewCount        int                  `json:"viewCount"`
	Author           *string              `json:"author,omitempty"`
	SortOrder        *int                 `json:"sortOrder,omitempty"`
	CreateTime       *time.Time           `json:"createTime,omitempty"`
	PublishedTime    *time.Time           `json:"publishedTime,omitempty"`
	ReadingTime      *int                 `json:"readingTime,omitempty"`
	Tags             *string              `json:"tags,omitempty"`
	Excerpt          *string              `json:"excerpt,omitempty"`
	ImageAltTag      *string              `json:"imageAltTag,omitempty"`
	Categories       [][]Category         `json:"categories,omitempty"`
	AdditionalFields *AdditionalFields    `json:"additionalFields,omitempty"`
	AuthorDetails    *Author              `json:"authorDetails,omitempty"`
	MemberProfile    *MemberProfile       `json:"memberProfile,omitempty"`
	TenantID         string               `json:"tenantId"`
	ContentChunk     *Chunk               `json:"contentChunk,omitempty"`
	CtaLink          *string              `json:"ctaLink,omitempty"`
	SavedFlag        *bool                `json:"savedFlag,omitempty"`
	PreviewLink      *string              `json:"PreviewLink,omitempty"`
	UUID             *string              `json:"Uuid,omitempty"`
}

type ChannelEntryDetails struct {
	ChannelEntriesList []ChannelEntries `json:"channelEntriesList"`
	Count              int              `json:"count"`
}

type Chunk struct {
	Data   []string `json:"data"`
	Length int      `json:"length"`
}

type CountUpdate struct {
	Count  int  `json:"count"`
	Status bool `json:"status"`
}

type Course struct {
	ID          int    `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	ImageName   string `json:"imageName"`
	ImagePath   string `json:"imagePath"`
	Category    int    `json:"category"`
	TenantID    string `json:"tenantId"`
}

type CourseDetails struct {
	Lesson  []Lesson   `json:"lesson"`
	Section []Sections `json:"section"`
}

type CourseLists struct {
	Courselist []Course `json:"courselist"`
	Count      int      `json:"count"`
}

type EntriesAdditionalData struct {
	AuthorDetails    graphql.Omittable[*bool] `json:"authorDetails,omitempty"`
	MemberProfile    graphql.Omittable[*bool] `json:"memberProfile,omitempty"`
	AdditionalFields graphql.Omittable[*bool] `json:"additionalFields,omitempty"`
	Categories       graphql.Omittable[*bool] `json:"categories,omitempty"`
	SavedList        graphql.Omittable[*bool] `json:"savedList,omitempty"`
	MemberID         graphql.Omittable[*int]  `json:"MemberId,omitempty"`
}

type EntriesFilter struct {
	ChannelID          graphql.Omittable[*int]    `json:"channelId,omitempty"`
	CategoryID         graphql.Omittable[*int]    `json:"categoryId,omitempty"`
	CategorySlug       graphql.Omittable[*string] `json:"categorySlug,omitempty"`
	GetChildCategories graphql.Omittable[*bool]   `json:"getChildCategories,omitempty"`
	Status             graphql.Omittable[*string] `json:"Status,omitempty"`
	ChannelName        graphql.Omittable[*string] `json:"ChannelName,omitempty"`
}

type EntrySave struct {
	EntryID  int    `json:"entryId"`
	UserID   int    `json:"userId"`
	TenantID string `json:"tenantId"`
	Save     bool   `json:"save"`
}

type Field struct {
	ID               int            `json:"id"`
	FieldName        string         `json:"fieldName"`
	FieldTypeID      int            `json:"fieldTypeId"`
	MandatoryField   int            `json:"mandatoryField"`
	OptionExist      int            `json:"optionExist"`
	CreatedOn        time.Time      `json:"createdOn"`
	CreatedBy        int            `json:"createdBy"`
	ModifiedOn       *time.Time     `json:"modifiedOn,omitempty"`
	ModifiedBy       *int           `json:"modifiedBY,omitempty"`
	FieldDesc        string         `json:"fieldDesc"`
	OrderIndex       int            `json:"orderIndex"`
	ImagePath        string         `json:"imagePath"`
	DatetimeFormat   *string        `json:"datetimeFormat,omitempty"`
	TimeFormat       *string        `json:"timeFormat,omitempty"`
	SectionParentID  *int           `json:"sectionParentId,omitempty"`
	CharacterAllowed *int           `json:"characterAllowed,omitempty"`
	FieldTypeName    string         `json:"fieldTypeName"`
	FieldValue       *FieldValue    `json:"fieldValue,omitempty"`
	FieldOptions     []FieldOptions `json:"fieldOptions,omitempty"`
	TenantID         string         `json:"tenantId"`
}

type FieldOptions struct {
	ID          int        `json:"id"`
	OptionName  string     `json:"optionName"`
	OptionValue string     `json:"optionValue"`
	CreatedOn   time.Time  `json:"createdOn"`
	CreatedBy   int        `json:"createdBy"`
	ModifiedOn  *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy  *int       `json:"modifiedBY,omitempty"`
	TenantID    string     `json:"tenantId"`
}

type FieldValue struct {
	ID         int        `json:"id"`
	FieldValue string     `json:"fieldValue"`
	CreatedOn  time.Time  `json:"createdOn"`
	CreatedBy  int        `json:"createdBy"`
	ModifiedOn *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy *int       `json:"modifiedBY,omitempty"`
	TenantID   string     `json:"tenantId"`
}

type Filter struct {
	Limit      graphql.Omittable[*int]    `json:"limit,omitempty"`
	Offset     graphql.Omittable[*int]    `json:"offset,omitempty"`
	IsActive   graphql.Omittable[*bool]   `json:"isActive,omitempty"`
	Keyword    graphql.Omittable[*string] `json:"keyword,omitempty"`
	Location   graphql.Omittable[*string] `json:"location,omitempty"`
	Experience graphql.Omittable[*string] `json:"Experience,omitempty"`
	Posteddate graphql.Omittable[*string] `json:"posteddate,omitempty"`
}

type ForgotPasswordResponse struct {
	Message string `json:"message"`
	Success bool   `json:"success"`
}

type GeneralInfo struct {
	CompanyName    string `json:"companyName"`
	LogoPath       string `json:"logoPath"`
	ExpandLogoPath string `json:"expandLogoPath"`
	TenantID       string `json:"tenantId"`
}

type Lesson struct {
	ID         int    `json:"id"`
	CourseID   int    `json:"courseId"`
	SectionID  int    `json:"sectionId"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	EmbedLink  string `json:"embedLink"`
	FileName   string `json:"fileName"`
	FilePath   string `json:"filePath"`
	LessonType string `json:"lessonType"`
	OrderIndex int    `json:"orderIndex"`
	TenantID   string `json:"tenantId"`
}

type MemberArguments struct {
	Module   graphql.Omittable[*int]    `json:"module,omitempty"`
	TenantID graphql.Omittable[*string] `json:"tenantId,omitempty"`
}

type MemberCheckLoginResponse struct {
	Email         bool     `json:"email"`
	Password      bool     `json:"password"`
	Message       string   `json:"message"`
	Token         string   `json:"token"`
	Success       bool     `json:"success"`
	MemberDetails *Members `json:"memberDetails,omitempty"`
}

type MemberDetails struct {
	ID               graphql.Omittable[*int]    `json:"id,omitempty"`
	FirstName        string                     `json:"firstName"`
	LastName         graphql.Omittable[*string] `json:"lastName,omitempty"`
	Mobile           graphql.Omittable[*string] `json:"mobile,omitempty"`
	Email            string                     `json:"email"`
	Password         string                     `json:"password"`
	IsActive         graphql.Omittable[*int]    `json:"isActive,omitempty"`
	ProfileImage     graphql.Omittable[*string] `json:"profileImage,omitempty"`
	ProfileImagePath graphql.Omittable[*string] `json:"profileImagePath,omitempty"`
	Username         graphql.Omittable[*string] `json:"username,omitempty"`
	GroupID          graphql.Omittable[*int]    `json:"groupId,omitempty"`
	UserID           int                        `json:"userId"`
	TenantID         string                     `json:"tenantId"`
	Message          graphql.Omittable[*string] `json:"message,omitempty"`
}

type MemberInfo struct {
	Email    string `json:"email"`
	TenantID string `json:"tenantId"`
	URL      string `json:"url"`
}

type MemberProfile struct {
	ID              int        `json:"id"`
	MemberID        int        `json:"memberId"`
	ProfileName     string     `json:"profileName"`
	ProfileSlug     string     `json:"profileSlug"`
	ProfilePage     *string    `json:"profilePage,omitempty"`
	MemberDetails   any        `json:"memberDetails,omitempty"`
	CompanyName     *string    `json:"companyName,omitempty"`
	CompanyLocation *string    `json:"companyLocation,omitempty"`
	CompanyLogo     *string    `json:"companyLogo,omitempty"`
	About           *string    `json:"about,omitempty"`
	SeoTitle        *string    `json:"seoTitle,omitempty"`
	SeoDescription  *string    `json:"seoDescription,omitempty"`
	SeoKeyword      *string    `json:"seoKeyword,omitempty"`
	Linkedin        *string    `json:"linkedin,omitempty"`
	Twitter         *string    `json:"twitter,omitempty"`
	Website         *string    `json:"website,omitempty"`
	CreatedBy       *int       `json:"createdBy,omitempty"`
	CreatedOn       *time.Time `json:"createdOn,omitempty"`
	ModifiedOn      *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy      *int       `json:"modifiedBy,omitempty"`
	ClaimStatus     *int       `json:"claimStatus,omitempty"`
	IsActive        *int       `json:"IsActive,omitempty"`
	TenantID        string     `json:"tenantId"`
	ClaimDate       *time.Time `json:"claimDate,omitempty"`
}

type MemberResetpassInfo struct {
	NewPassword     string `json:"newPassword"`
	ConfrimPassword string `json:"confrimPassword"`
	Token           string `json:"token"`
}

type MemberSettings struct {
	ID                int        `json:"id"`
	AllowRegistration int        `json:"allowRegistration"`
	MemberLogin       string     `json:"memberLogin"`
	ModifiedBy        *int       `json:"modifiedBy,omitempty"`
	ModifiedOn        *time.Time `json:"modifiedOn,omitempty"`
	NotificationUsers string     `json:"notificationUsers"`
	TenantID          string     `json:"tenantId"`
}

type MemberSignin struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	UserID   int    `json:"userId"`
	TenantID string `json:"tenantId"`
}

type Members struct {
	ID               *int       `json:"Id,omitempty"`
	FirstName        string     `json:"firstName"`
	LastName         *string    `json:"lastName,omitempty"`
	Mobile           *string    `json:"mobile,omitempty"`
	Email            string     `json:"email"`
	Password         string     `json:"password"`
	IsActive         *int       `json:"isActive,omitempty"`
	ProfileImage     *string    `json:"profileImage,omitempty"`
	ProfileImagePath *string    `json:"profileImagePath,omitempty"`
	Username         *string    `json:"username,omitempty"`
	GroupID          *int       `json:"groupId,omitempty"`
	CreatedBy        *int       `json:"createdBy,omitempty"`
	CreatedOn        *time.Time `json:"createdOn,omitempty"`
	ModifiedOn       *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy       *int       `json:"modifiedBy,omitempty"`
	TenantID         string     `json:"tenantId"`
	IsDeleted        int        `json:"isDeleted"`
	StorageType      *string    `json:"storageType,omitempty"`
	NameString       *string    `json:"NameString,omitempty"`
}

type MembersDetails struct {
	MembersList []Members `json:"membersList"`
	Count       int       `json:"count"`
}

type Mutation struct {
}

type Query struct {
}

type Section struct {
	ID            int        `json:"id"`
	SectionName   string     `json:"sectionName"`
	SectionTypeID int        `json:"sectionTypeId"`
	CreatedOn     time.Time  `json:"createdOn"`
	CreatedBy     int        `json:"createdBy"`
	ModifiedOn    *time.Time `json:"modifiedOn,omitempty"`
	ModifiedBy    *int       `json:"modifiedBY,omitempty"`
	OrderIndex    int        `json:"orderIndex"`
	TenantID      string     `json:"tenantId"`
}

type Sections struct {
	ID         int    `json:"id"`
	CourseID   int    `json:"courseId"`
	Title      string `json:"title"`
	Content    string `json:"content"`
	OrderIndex int    `json:"orderIndex"`
	TenantID   string `json:"tenantId"`
}

type SocialLoginInput struct {
	FirstName string                     `json:"firstName"`
	LastName  graphql.Omittable[*string] `json:"lastName,omitempty"`
	Email     string                     `json:"email"`
	Password  graphql.Omittable[*string] `json:"password,omitempty"`
	Username  graphql.Omittable[*string] `json:"username,omitempty"`
}

type SocialLoginResponse struct {
	Message string `json:"message"`
	Token   string `json:"token"`
	Userid  int    `json:"userid"`
}

type Sort struct {
	SortBy graphql.Omittable[*string] `json:"sortBy,omitempty"`
	Order  graphql.Omittable[*int]    `json:"order,omitempty"`
}

type UpdateMember struct {
	ID               int                           `json:"Id"`
	FirstName        string                        `json:"firstName"`
	LastName         graphql.Omittable[*string]    `json:"lastName,omitempty"`
	Mobile           string                        `json:"mobile"`
	Email            string                        `json:"email"`
	Password         graphql.Omittable[*string]    `json:"password,omitempty"`
	IsActive         graphql.Omittable[*int]       `json:"isActive,omitempty"`
	ProfileImage     graphql.Omittable[*string]    `json:"profileImage,omitempty"`
	ProfileImagePath graphql.Omittable[*string]    `json:"profileImagePath,omitempty"`
	Username         graphql.Omittable[*string]    `json:"username,omitempty"`
	GroupID          graphql.Omittable[*int]       `json:"groupId,omitempty"`
	CreatedBy        graphql.Omittable[*int]       `json:"createdBy,omitempty"`
	CreatedOn        graphql.Omittable[*time.Time] `json:"createdOn,omitempty"`
	ModifiedOn       graphql.Omittable[*time.Time] `json:"modifiedOn,omitempty"`
	ModifiedBy       graphql.Omittable[*int]       `json:"modifiedBy,omitempty"`
	TenantID         graphql.Omittable[*string]    `json:"tenantId,omitempty"`
	RemoveImage      graphql.Omittable[*bool]      `json:"removeImage,omitempty"`
}

type UpdatememberResponse struct {
	MemberDetails *Members `json:"memberDetails"`
	Message       string   `json:"message"`
}
