package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"
	"spurt-cms/graphql/controller"
	"spurt-cms/graphql/model"
)

// CourseList is the resolver for the CourseList field.
func (r *queryResolver) CourseList(ctx context.Context, tenantID *string, status *int, categoryID *int) (*model.CourseLists, error) {
	return controller.CourseList(ctx, tenantID, status, categoryID)
}

// CoursedetailList is the resolver for the CoursedetailList field.
func (r *queryResolver) CoursedetailList(ctx context.Context, tenantID *string, courseID *int) (*model.CourseDetails, error) {
	return controller.CourseDetails(ctx, tenantID, courseID)
}
