package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"spurt-cms/graphql/controller"
	"spurt-cms/graphql/model"
)

// MemberRegister is the resolver for the memberRegister field.
func (r *mutationResolver) MemberRegister(ctx context.Context, input model.MemberDetails, arguments *model.MemberArguments) (bool, error) {
	return controller.MemberRegister(ctx, &input, arguments)
}

// MembersList is the resolver for the MembersList field.
func (r *queryResolver) MembersList(ctx context.Context, filter *model.Filter) (*model.MembersDetails, error) {
	return controller.MembersList(ctx, filter)
}
