template_name: "Support Sphere"
# template_image: "/image-resize?name=/media/KnowledgeBase.jpg"
template_image: "/websites/public/img/Help center home screen.jpg"
description: "A support sphere template visually represents layers of support or assistance, showing how resources or help radiate outward from a central point."
type: "Knowledge base"
channel: "Blog,Knowledge Base"

